machine:
  node:
    version: v10.9.0
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

test:
  override:
    - eslint --debug . --format tap | tap-xunit > ${CIRCLE_TEST_REPORTS}/lint.xml && test ${PIPESTATUS[0]} -eq 0
    - NODE_PATH=source babel-node source/test | tap-xunit > ${CIRCLE_TEST_REPORTS}/test.xml && test ${PIPESTATUS[0]} -eq 0
    - yarn run build:client
    - yarn run build:server
    - yarn run start
    - REPORT_DIR=${CIRCLE_TEST_REPORTS} LOG_DIR=${CIRCLE_ARTIFACTS} yarn run test:e2e

general:
  artifacts:
    - reports
